const formas = [
  {
    categoria: "Transporte",
    cards: [
      {
        titulo: "Usar transporte público o alternativa",
        resumen: "Si tienes la oportunidad de ir en bicicleta o en ",
        resto: "transporte público, puedes reducir drásticamente tus emisiones de carbono.",
        min: 0.6,
        max: 1,
        med: 0.8,
        img: "transporte publico.jpg",
      },
      {
        titulo: "Compartir transporte privado",
        resumen: "Si compartes tu coche o le dices a un conocido ",
        resto:
          "que te lleve en su coche a un lugar a donde él también se dirige, quizá incluso te ayude a ahorrar algo de dinero si comparten las cuentas.",
        min: 0,
        max: 1,
        med: 0.3,
        img: "compartir transporte.jpg",
      },
      {
        titulo: "Conducir eficientemente",
        resumen: "No, quizá no lo estés haciendo. Lee las ",
        resto:
          "siguientes recomendaciones para manejar eficientemente antes de seleccionar que ya haces esto: <a href='https://www.conduccioneficiente.cl' target='blank'>Conducción eficiente</a>. Ahí se muestran muchos tips para ahorrar combustible. Te ayudará también a ahorrar dinero.",
        min: 0.01,
        max: 1.46,
        med: 0.3,
        img: "conducir eficientemente.jpg",
      },
      {
        titulo: "Cambiarse a un híbrido",
        resumen: "¡Cuidado! Esto tiene trampa: si la red eléctrica ",
        resto:
          "de tu localidad genera la energía con combustión fósil, termina siendo mejor usar un coche de gasolina. Además, no debes cambiar de coche a menos que tenga por lo menos 76,000 KM, aproximadamente. Por esto mismo, resulta que hacer este cambio puede ser incluso contraproducente, dependiendo de dónde vivas.",
        min: -0.2,
        max: 3.1,
        med: 0.7,
        img: "coche híbrido.jpg",
      },
      {
        titulo: "Carro 100% eléctrico",
        resumen: "¡Cuidado! Esto tiene trampa: si la red eléctrica ",
        resto:
          "de tu localidad genera la energía con combustión fósil, termina siendo mejor usar un coche de gasolina. Además, no debes cambiar de coche a menos que tenga por lo menos 76,000 KM, aproximadamente. Por esto mismo, resulta que hacer este cambio puede ser incluso contraproducente, dependiendo de dónde vivas.",
        min: -1.9,
        max: 5.4,
        med: 2,
        img: "coche eléctrico.jpg",
      },
      {
        titulo: "Vivir sin coche",
        resumen: "No compres un coche. Ten a la mano la bicicleta ",
        resto: "y usa transportes públicos o compartidos como alternativa.",
        min: 0.6,
        max: 3.6,
        med: 0,
        img: "vivir sin carro.jpg",
      },
      {
        titulo: "Trabajar desde casa",
        resumen: "Así no tienes que usar un transporte.",
        resto: "",
        min: 0.1,
        max: 1.4,
        med: 0.4,
        img: "trabajar desde casa.jpg",
      },
      {
        titulo: "Evitar un vuelo largo",
        resumen: "Los combustibles necesarios para un vuelo de ",
        resto:
          "avión son muy contaminantes. Siempre es más ecológico en camión o incluso en tren, aunque esto no siempre sea lo más económico, claro.",
        min: 0.7,
        max: 4.5,
        med: 1.9,
        img: "vuelo largo.png",
      },
      {
        titulo: "Evitar un vuelo corto",
        resumen: "Al evitar un vuelo corto también puedes ayudar ",
        resto: "a reducir tu huella de carbono. Viajar en camión o incluso en tren es mejor, aunque sea menos económico e incluso práctico.",
        min: 0.2,
        max: 1.5,
        med: 0.6,
        img: "vuelo corto.jpg",
      },
    ],
  },
  {
    categoria: "Dieta",
    cards: [
      {
        titulo: "Seguir una dieta saludable",
        resumen: "Una dieta saludable tiene menos carnes rojas ",
        resto:
          "y procesados. Básicamente es hacerle caso a los nutricionistas. La ganadería contamina mucho, y reducir el consumo de carnes ayudará a contaminar menos.",
        min: 0.01,
        max: 1.3,
        med: 0.3,
        img: "dieta saludable.jpg",
      },
      {
        titulo: "Dieta vegana",
        resumen: "Nada de producto animal. Al contrario de",
        resto:
          " lo que muchos piensan, los nutricionistas no han encontrado que una dieta vegana repercuta negativamente en la salud, pero solo si se sigue correctamente. Si planeas intentar esto, es recomendable acudir a un profesional.",
        min: 0.4,
        max: 2.1,
        med: 0.9,
        img: "dieta vegana.jpg",
      },
      {
        titulo: "Dieta vegetariana",
        resumen: "Sustituir la carne por alternativas vegetales. ",
        resto: "",
        min: 0.01,
        max: 1.5,
        med: 0.5,
        img: "dieta vegetariana.jpg",
      },
      {
        titulo: "Insectos como fuente de proteína",
        resumen: "Los insectos pueden proporcionar hasta 4 ",
        resto:
          "veces la cantidad de proteína que la carne, y liberan hasta <a href='https://comprarinsectoscomestibles.es/comer-insectos-comestibles-frenar-cambio-climatico/' target='blank'>2850 veces menos CO2</a> que la carne de vaca.<br>Por ejemplo, <a href='https://comprarinsectoscomestibles.es/insectos-comestibles-una-dieta-para-el-futuro-hoy/' target='blank'>si consumiéramos 100gms de  grillos nos aportarían 60 gms de proteína</a>, mientras que un filete de vacuno sólo 20gms.  A su vez nos daría el 20% de la fibra que necesitaríamos diariamente.<br>Existen proyectos como el <a href='https://thehiveexplorer.com/' target='blank'>Hive Explorer</a> que te ayudarán a generar tus propios insectos 100% comestibles. ¡No les tengas miedo, saben muy bien!",
        min: 0.01,
        max: 1.5,
        med: 0.5,
        img: "comer insectos.jpg",
      },
      {
        titulo: "No comer carne de vaca",
        resumen: "La carne de vaca o ternero es conocida",
        resto:
          " por ser la más contaminante de todas.<br>Puedes conocer las emisiones que causa cada alimento en <a href='https://ourworldindata.org/grapher/ghg-kcal-poore' target='blank'>esta tabla interactiva</a>.",
        min: 0,
        max: 1.25,
        med: 0.5,
        img: "no comer carne de vaca.jpg",
      },
      {
        titulo: "Consumir productos regionales o locales",
        resumen: "Los productos regionales no requieren",
        resto: " mucho transporte para llegar hasta ti, y tampoco necesitan ambientes controlados para crecer.",
        min: 0,
        max: 1.1,
        med: 0.4,
        img: "productos regionales o locales.jpg",
      },
      {
        titulo: "Consumir productos de temporada",
        resumen: "Aquellos productos que no requieren",
        resto:
          " calefactores ni tratos especiales  en cierta época del año, son los que se dan bien en esa temporada, por lo que se requiere menos energía para producirlos.",
        min: 0,
        max: 0.4,
        med: 0.2,
        img: "productos de temporada.jpg",
      },
      {
        titulo: "Producir tus propios cultivos o comida",
        resumen: "Ya sea que tengas un jardín con algunos",
        resto: " cultivos o una pequeña granja, producir tu propia comida siempre beneficia al medio ambiente.",
        min: null,
        max: null,
        med: 0.4,
        img: "propia comida.jpg",
      },
      {
        titulo: "Pedir comida ecológica en restaurantes",
        resumen: "Por lo que has leído arriba, algo ecológico",
        resto:
          " sería no pedir mucha carne (o directamente evitarla), preferir insectos, pedir productos de temporada y/o locales, entre otros.",
        min: null,
        max: null,
        med: 0.3,
        img: "restaurante comida buena.jpg",
      },
      {
        titulo: "Menos comida procesada / alcohol",
        resumen: "No hay mucho que decir: evita comer procesados y/o alcohol.",
        resto: "",
        min: null,
        max: null,
        med: 0.2,
        img: "no alcohol.jpg",
      },
    ],
  },
  {
    categoria: "El hogar",
    cards: [
      {
        titulo: "Generar tu propia energía renovable",
        resumen: "Compra unos paneles solares. Es muy bueno",
        resto: " para reducir tu huella de carbono.",
        min: 0.1,
        max: 4.8,
        med: 1.3,
        img: "propia energía renovable.jpg",
      },
      {
        titulo: "Comprar energía renovable",
        resumen: "Si en tu localidad existe un servicio que ofrezca",
        resto: " energía renovable, es buena idea comprarles esa valiosa energía.",
        min: 0.3,
        max: 2.5,
        med: 1.5,
        img: "comprar energía renovable.jpg",
      },
      {
        titulo: "Electrodomésticos más eficientes",
        resumen: "Estufa eléctrica, refrigerador moderno,",
        resto: " microondas de último año, etc. Todo ayuda.",
        min: 0.01,
        max: 0.3,
        med: 0.1,
        img: "estufa electrica.jpg",
      },
      {
        titulo: "Usar una bomba de calor",
        resumen: "Para calentar tu casa o el agua de la ducha,",
        resto: " usa una <a href='https://youtu.be/uHehqh6eGF8' target='blank'>bomba de calor</a>, que no ocupa gas fósil para funcionar.",
        min: 0.1,
        max: 1.3,
        med: 0.8,
        img: "bomba de calor.jpg",
      },
      {
        titulo: "Usar un boiler solar o similar",
        resumen: "Calentar tu casa o agua con métodos renovables",
        resto: " (pero si usarás una bomba de calor, no selecciones este, sino el de arriba).",
        min: 0.1,
        max: 1.3,
        med: 0.7,
        img: "boiler solar.jpg",
      },
      {
        titulo: "Ahorrar agua caliente cuando sea posible",
        resumen: "En verano, ¿para qué quieres agua caliente?",
        resto:
          " Es buena idea acostumbrarte a usar agua fría si el agua caliente no es estrictamente necesaria. Es más, si realmente te interesa el planeta, no usarás agua caliente casi ni en invierno.",
        min: 0.1,
        max: 0.6,
        med: 0.3,
        img: "agua caliente.jpg",
      },
      {
        titulo: "Mejor aislamiento",
        resumen: "No necesitas remodelar la casa, solo poner",
        resto:
          " algún aislamiento en el techo o las ventanas.<br>Identificar qué partes de la casa están peor aisladas y reforzarlas, tendrá un efecto positivo en el medio ambiente, porque se requerirá menos calefacción para mantener la casa a una temperatura adecuada.",
        min: null,
        max: null,
        med: 0.2,
        img: "aislar el techo.jpg",
      },
      {
        titulo: "Remodelación y renovación de la casa",
        resumen: "Esto tiene que involucrar remodelar las paredes,",
        resto:
          " quizá el techo. Es una remodelación para mejorar el aislamiento de la casa.<br>La idea es detectar qué partes de la casa están peor aisladas y reforzarlas.",
        min: 0,
        max: 1.9,
        med: 0.9,
        img: "aislar la casa.jpg",
      },
      {
        titulo: "Vivir en una casa pequeña / compartir vivienda",
        resumen: "",
        resto: "",
        min: 0,
        max: 1,
        med: 0.4,
        img: "casa pequeña.jpg",
      },
      {
        titulo: "¡Vivir en una casa pasiva!",
        resumen: "¿Que qué es una casa pasiva?",
        resto:
          " En <a href='https://youtu.be/n0CeNAEzsp8' target='_blank'>este video</a> puedes saber.<br>Pero en pocas palabras, una casa pasiva es aquella que está construida de cierta forma que la energía requerida para climatizarla sea mínima. Son realmente fabulosas, porque combinan muchas técnicas para lograr esta eficiencia tan elevada.<br>Puede parecer que no disminuyen mucho la huella de carbono, pero es que los materiales y la construcción tienen su impacto, aunque al fin y al cabo, los beneficios superan a los gastos y resulta conveniente.",
        min: 0.1,
        max: 0.9,
        med: 0.5,
        img: "casa pasiva.jpg",
      },
    ],
  },
  {
    categoria: "Otras cosas",
    cards: [
      {
        titulo: "Vivir sin mascotas",
        resumen: "Así es, tus mascotas son muy contaminantes, lamento decirlo.",
        resto: "",
        min: 0.01,
        max: 2.4,
        med: 0.8,
        img: "no mascotas.jpg",
      },
      {
        titulo: "Menos compras y/o herramientas más duraderas",
        resumen: "Evidentemente, si consumes menos y",
        resto: " compras productos duraderos, pues ayudas al medio ambiente.",
        min: 0,
        max: 0.35,
        med: 0.15,
        img: "menos productos.jpg",
      },
      {
        titulo: "Reciclar",
        resumen: "Aunque no lo parezca, reciclar no es",
        resto:
          " la mejor forma de reducir la huella de carbono según algunos estudios, aunque <b>sí que es excelente</b> para otros propósitos igualmente importantes, como reducir la cantidad de materia prima que consumimos. Si ya lo haces, ¡sigue así!",
        min: 0,
        max: 0.3,
        med: 0.1,
        img: "reciclar.jpg",
      },
      // {
      //   titulo: "Compartir bienes o servicios",
      //   resumen: "Optar por servicios locales o comunitarios, compartir y reparar",
      //   resto:
      //     " las herramientas o bienes que se puedan, compartir la vivienda. Aunque estudios apuntan que estrategias de parejas como estas no ayudan a reducir nada, porque de todos modos el consumo es el doble, pero aún así existen otros que afirman que sí podría suponer una reducción. De cualquier forma, vale la pena intentarlo.",
      //   min: 0,
      //   max: 0.3,
      //   med: 0.1,
      //   img: "compartir bienes.jpg",
      // },
    ],
  },
];
